Bind only to localhost by default
MelbourneHighSchoolRobotics/ev3sim pull request #58
Opened 2020-08-28 13:33 UTC by platy11

This PR:
- sets `ev3sim` to only bind to localhost (::1) by default
- adds flags (`--simulator_addr` for `ev3attach` and `--bind_addr` for `ev3sim`) to allow users to listen on all interfaces or use a different port if they want to for whatever reason

Note that this PR targets main, but was based on batched_commands so should be merged after #53. 
I haven't tested this on Windows yet, presumably it works but it would be best to check.

2020-08-28 13:35 UTC, platy11 commented
To compare to `batched_commands`: https://github.com/MelbourneHighSchoolRobotics/ev3sim/compare/batched_commands...platy11:bind-to-localhost

2020-08-28 13:45 UTC, platy11 commented on LICENSE
> +Copyright 2020 the Melbourne High School ev3sim authors
See https://opensource.stackexchange.com/questions/5508/what-does-and-contributors-in-the-copyright-byline-imply

2020-08-28 13:55 UTC, glipR commented
Looks good to me, probably should have done this originally, thanks for the PR :)

2020-08-28 13:57 UTC, glipR commented on LICENSE
> +Copyright 2020 the Melbourne High School ev3sim authors
I'd want an ok from @peter-drew or @Dalordish before merging :) I've got no idea if we want to separate ev3sim from Melbourne High School organisation, and move towards "all contributors on the repo"

2020-08-28 15:28 UTC, Dalordish commented on LICENSE
> +Copyright 2020 the Melbourne High School ev3sim authors
At risk of exposing myself as being awake way too late into the night, a few thoughs on this:

**tl;dr this is fine**

Max is correct in that contributors to the repo each own their individual copyright to the code that they write, despite being merged to the repo. This copyright applies regardless of any byline or notice - having it there is just being explicit. 

Fortunately, under the github terms of service, as well as common understanding, although I don't believe this has ever been tested before, contributions to a project containing notice of a license are implicitly licensed under the same terms. Because we use the permissive BSD-3 license, this means we can do whatever we want with the code. (If you want to be explicitly clear, section 6. Contributoins Under Repository License, here https://docs.github.com/en/github/site-policy/github-terms-of-service )

In other words, IANAL, but there shouldn't be any legal difference from including this notice, and we're protected from say, copyright owners revoking our ability to use their contributions by the license.

2020-08-28 15:29 UTC, Dalordish commented on LICENSE
> +Copyright 2020 the Melbourne High School ev3sim authors
I would leave it as "Melbourne High School" rather than "the Melbourne High School". Melbourne High School refers to the legal entity named "Melbourne High School", whereas "the Melbourne High School" is both incorrect in referring to the entitiy (think of saying "The Apple", or "The Google"), as well as in it's other interpretation (the single high school in melbourne)

2020-08-28 15:35 UTC, Dalordish commented on LICENSE
> +Copyright 2020 the Melbourne High School ev3sim authors
Lastly, and this is less relevant to this directly, but attribution raises an important point, which is making sure we recognise contributors for their work - this not only gives people the warm fuzzies, but it also encourages other people to contribute. I think either a  CONTRIBUTORS.md, or using the all-contributors specification (https://github.com/all-contributors/all-contributors) would be nice. Happy to discuss this further in a different thread, but I thought it would be worth noting here in case I forget.

2020-08-28 22:47 UTC, glipR commented on LICENSE
> +Copyright 2020 the Melbourne High School ev3sim authors
all contributors looks great! I might look at adding the bot to our repo later today.

2020-08-29 01:16 UTC, peter-drew commented on LICENSE
> +Copyright 2020 the Melbourne High School ev3sim authors
I like
> Copyright 2020 Melbourne High School and contributors

2020-08-29 01:19 UTC, peter-drew requested changes
Either adjust the license as per comments, or move change to separate PR

2020-08-29 03:01 UTC, platy11 commented on LICENSE
> +Copyright 2020 the Melbourne High School ev3sim authors
Great, I'll change it to "Melbourne High School and contributors" then.
+1 for all-contributors as well.

2020-08-29 03:48 UTC, Dalordish approved these changes
LGTM, ship it 🚀

2020-08-29 06:11 UTC, glipR approved these changes

2020-08-29 06:13 UTC, peter-drew approved these changes

2020-08-29 06:14 UTC, merged