Mock print to send logs via gRPC
MelbourneHighSchoolRobotics/ev3sim pull request #62
Opened 2020-08-29 05:36 UTC by platy11

This PR:
- adds a mock for `print` that sends logs to the simulator process via gRPC
- adds an option `--send_logs` to `ev3attach` where logs will be printed in the simulator process and not the robot process
- changes `ev3sim` to run `ev3attach` with the `--send_logs` flag when running a batch command

The PR is based on bind-to-localhost so should be merged after #58. To see just the changes from this PR: https://github.com/platy11/ev3sim/compare/bind-to-localhost...grpc-send-logs

2020-08-29 05:57 UTC, glipR commented on ev3sim/attach.py
> +                data['actions_queue'].put(('send_log', message))
think it would be best to send `message + end` here, and then setting `end=''` in `communication.py`, so that the `end` parameter works as expected.

To fix an extra tag getting appended in `communication.py`, If request.log[-1] == '\n', then don't add the tag to that line. (Also remove the `rstrip` there)

2020-08-29 06:05 UTC, glipR commented on ev3sim/attach.py
> +                        tag = ''
I think it's probably safer to bring your mock out of the robot function, and mock print in the robot, write and comms functions, so that any prints inadvertently called in the other threads are also sent through. This also allows us to tag each print with comms/write/robot, for further logging (We'd just modify the mock for each function slightly).

2020-08-29 06:06 UTC, glipR commented on ev3sim/batched_run.py
> +    time.sleep(0.5) # Give the gRPC server 500ms to start
forgot about this, thanks

2020-08-29 06:08 UTC, glipR requested changes
Looks great, thanks again for the effort.

Happy to approve this once the above comments are resolved, or there's reason enough to keep the code as is 👍

2020-08-29 10:59 UTC, platy11 commented on ev3sim/attach.py
> +                data['actions_queue'].put(('send_log', message))
Thanks, I've pushed a new commit that addresses this

2020-08-29 11:07 UTC, glipR commented on ev3sim/attach.py
> +                        tag = ''
The print change in the previous commit in the `comms` function doesn't seem to use the mocked print, since still only `robot` is mocked. (Apologies if this is not the case, I haven't tested yet)

Also, going to merge another PR which modifies `attach.py`, apologies for any conflicts.

2020-08-30 06:46 UTC, platy11 commented on ev3sim/attach.py
> +                        tag = ''
@glipR Yeah, I hadn't moved the print mock yet. I've started on this in my newest commit, although it doesn't seem to work correctly and I'm not sure why. Here's the output of my current changes:
```
Loading chipmunk for Linux (64bit) [/home/max/.local/lib/python3.8/site-packages/pymunk/libchipmunk.so]
pygame 1.9.6
Hello from the pygame community. https://www.pygame.org/contribute.html
[Robot-0/comms] comms
[Robot-0/write] write
[Robot-0/robot] comms>with
[Robot-0/robot] comms>with>try
[Robot-0/robot] write>with
[Robot-0/robot] write>with>try
[Robot-0/robot] Connection initialised.
[Robot-0/robot] Hello from the simulator!!!
```
The lines starting with `comms` are printed from the `comms` function, and `write` from `write`. For some reason, anything within the [`with grpc.insecure_channel(args.simulator_addr)`](https://github.com/platy11/ev3sim/blob/grpc-send-logs/ev3sim/attach.py#L43) block seems to be using the mock from the `robot` function.

2020-08-30 06:50 UTC, platy11 commented on ev3sim/simulation/communication.py
> +                    tag = f'[{request.robot_id}{source_name}] '
I started including the source of the log in the tag, but I'm not sure if we will want to keep it like this. Maybe there's a better way to show that information, or we could just not print it for now.

2020-08-30 06:58 UTC, platy11 commented
Currently running `ev3attach --send_logs` prints the following warning:
```
WARNING:ev3dev2.button:Import warning: Failed to import "evdev". Button will be unusable!
```
This is generated [here](https://github.com/ev3dev/ev3dev-lang-python/blob/1471dc0c9b233dde62a9f8a7699864fd7aabb917/ev3dev2/button.py#L209), and is printed with `logging.Logger.warning` so isn't caught by the print mock. We could possibly look into mocking parts of `logging` as well, which I think would also allow us to control the display of exception traces. Alternatively, we could try and mock `sys.stdout`, but since that behaves like a file the mock would have to work a bit differently.

2020-08-30 08:11 UTC, glipR commented on ev3sim/simulation/communication.py
> +                    tag = f'[{request.robot_id}{source_name}] '
I think for now we don't want to print the source, it'd more be just for saved logs later on once the project has some more detailed logging of the internal methods.

2020-08-30 08:17 UTC, glipR commented on ev3sim/attach.py
> +                        tag = ''
That is very weird. Having a look locally now.

2020-08-30 08:19 UTC, glipR commented
Regarding the ev3dev logging, I'm not really too fussed currently. If we can get the print mock working then that's good enough for now. Unless you'd like to put more effort into a mock of stdout, then we can stick with this.

If we can't find a way to fix the `insecure_channel` problems then we can just remove the source for now and merge :)

2020-08-30 08:28 UTC, glipR commented on ev3sim/attach.py
> +                        tag = ''
Ok this seems completely random, but heavily favouring `robot`. I got `write>with>try` to come from the write thread once, and have also got two bots to send from different areas using the batch commands.

2020-08-30 08:34 UTC, glipR commented on ev3sim/attach.py
> +                        tag = ''
Alright, seems that `mock` doesn't work as we'd like for threads, so the `robot` mock overwrites the other two, once the thread is started up.

2020-08-30 08:50 UTC, glipR commented
@platy11 was able to fix by determining source based on thread id, and only mocking print once (Before starting the threads up).

Everytime we edit this file it gets uglier and uglier :p

Happy to merge this in its current state, unless you want to try the `stdout` mock instead.

2020-08-30 08:52 UTC, glipR approved these changes

2020-08-30 11:32 UTC, platy11 commented
Great, thanks for fixing that. I think we can leave the stdout mock for now, since it works like a file mocking it would probably require a lot of changes from what we currently have.
I'll just remove the source printing and this should be good to merge.

2020-08-30 11:38 UTC, merged